// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ddb.proto

package network.proto;

public final class DdbProto {
  private DdbProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveTableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveTableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteTempTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteTempTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteTempTableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteTempTableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExecuteNonQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExecuteNonQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExecuteNonQueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExecuteNonQueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExecuteQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExecuteQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExecuteQueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExecuteQueryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tddb.proto\"<\n\014TableRequest\022\032\n\rtempTable" +
      "Name\030\001 \001(\tH\000\210\001\001B\020\n\016_tempTableName\"V\n\rTab" +
      "leResponse\022\032\n\rattributeMeta\030\001 \001(\tH\000\210\001\001\022\027" +
      "\n\017attributeValues\030\002 \003(\tB\020\n\016_attributeMet" +
      "a\"\177\n\020SaveTableRequest\022\026\n\ttableName\030\001 \001(\t" +
      "H\000\210\001\001\022\032\n\rattributeMeta\030\002 \001(\tH\001\210\001\001\022\027\n\017att" +
      "ributeValues\030\003 \003(\tB\014\n\n_tableNameB\020\n\016_att" +
      "ributeMeta\"5\n\021SaveTableResponse\022\024\n\007succe" +
      "ss\030\001 \001(\010H\000\210\001\001B\n\n\010_success\"F\n\026DeleteTempT" +
      "ableRequest\022\032\n\rtempTableName\030\001 \001(\tH\000\210\001\001B" +
      "\020\n\016_tempTableName\";\n\027DeleteTempTableResp" +
      "onse\022\024\n\007success\030\001 \001(\010H\000\210\001\001B\n\n\010_success\"2" +
      "\n\026ExecuteNonQueryRequest\022\020\n\003sql\030\001 \001(\tH\000\210" +
      "\001\001B\006\n\004_sql\";\n\027ExecuteNonQueryResponse\022\024\n" +
      "\007success\030\001 \001(\010H\000\210\001\001B\n\n\010_success\"/\n\023Execu" +
      "teQueryRequest\022\020\n\003sql\030\001 \001(\tH\000\210\001\001B\006\n\004_sql" +
      "\"]\n\024ExecuteQueryResponse\022\032\n\rattributeMet" +
      "a\030\001 \001(\tH\000\210\001\001\022\027\n\017attributeValues\030\002 \003(\tB\020\n" +
      "\016_attributeMeta2\264\002\n\nDdbService\022-\n\014Reques" +
      "tTable\022\r.TableRequest\032\016.TableResponse\0222\n" +
      "\tSaveTable\022\021.SaveTableRequest\032\022.SaveTabl" +
      "eResponse\022@\n\013DeleteTable\022\027.DeleteTempTab" +
      "leRequest\032\030.DeleteTempTableResponse\022D\n\017E" +
      "xecuteNonQuery\022\027.ExecuteNonQueryRequest\032" +
      "\030.ExecuteNonQueryResponse\022;\n\014ExecuteQuer" +
      "y\022\024.ExecuteQueryRequest\032\025.ExecuteQueryRe" +
      "sponseB!\n\rnetwork.protoB\010DdbProtoP\001\242\002\003HL" +
      "Wb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TableRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TableRequest_descriptor,
        new java.lang.String[] { "TempTableName", "TempTableName", });
    internal_static_TableResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TableResponse_descriptor,
        new java.lang.String[] { "AttributeMeta", "AttributeValues", "AttributeMeta", });
    internal_static_SaveTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SaveTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveTableRequest_descriptor,
        new java.lang.String[] { "TableName", "AttributeMeta", "AttributeValues", "TableName", "AttributeMeta", });
    internal_static_SaveTableResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SaveTableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveTableResponse_descriptor,
        new java.lang.String[] { "Success", "Success", });
    internal_static_DeleteTempTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DeleteTempTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteTempTableRequest_descriptor,
        new java.lang.String[] { "TempTableName", "TempTableName", });
    internal_static_DeleteTempTableResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_DeleteTempTableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteTempTableResponse_descriptor,
        new java.lang.String[] { "Success", "Success", });
    internal_static_ExecuteNonQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ExecuteNonQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExecuteNonQueryRequest_descriptor,
        new java.lang.String[] { "Sql", "Sql", });
    internal_static_ExecuteNonQueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ExecuteNonQueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExecuteNonQueryResponse_descriptor,
        new java.lang.String[] { "Success", "Success", });
    internal_static_ExecuteQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ExecuteQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExecuteQueryRequest_descriptor,
        new java.lang.String[] { "Sql", "Sql", });
    internal_static_ExecuteQueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ExecuteQueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExecuteQueryResponse_descriptor,
        new java.lang.String[] { "AttributeMeta", "AttributeValues", "AttributeMeta", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
