// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ddb.proto

package network.proto;

public interface DeleteTempTableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteTempTableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string tempTableName = 1;</code>
   * @return Whether the tempTableName field is set.
   */
  boolean hasTempTableName();
  /**
   * <code>optional string tempTableName = 1;</code>
   * @return The tempTableName.
   */
  java.lang.String getTempTableName();
  /**
   * <code>optional string tempTableName = 1;</code>
   * @return The bytes for tempTableName.
   */
  com.google.protobuf.ByteString
      getTempTableNameBytes();
}
