// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ddb.proto

package network.proto;

public interface ExecuteNonQueryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExecuteNonQueryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool success = 1;</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <code>optional bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
