// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ddb.proto

package network.proto;

public interface ExecuteNonQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExecuteNonQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string sql = 1;</code>
   * @return Whether the sql field is set.
   */
  boolean hasSql();
  /**
   * <code>optional string sql = 1;</code>
   * @return The sql.
   */
  java.lang.String getSql();
  /**
   * <code>optional string sql = 1;</code>
   * @return The bytes for sql.
   */
  com.google.protobuf.ByteString
      getSqlBytes();
}
