// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ddb.proto

package network.proto;

public interface SaveTableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveTableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string tableName = 1;</code>
   * @return Whether the tableName field is set.
   */
  boolean hasTableName();
  /**
   * <code>optional string tableName = 1;</code>
   * @return The tableName.
   */
  java.lang.String getTableName();
  /**
   * <code>optional string tableName = 1;</code>
   * @return The bytes for tableName.
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <code>optional string attributeMeta = 2;</code>
   * @return Whether the attributeMeta field is set.
   */
  boolean hasAttributeMeta();
  /**
   * <code>optional string attributeMeta = 2;</code>
   * @return The attributeMeta.
   */
  java.lang.String getAttributeMeta();
  /**
   * <code>optional string attributeMeta = 2;</code>
   * @return The bytes for attributeMeta.
   */
  com.google.protobuf.ByteString
      getAttributeMetaBytes();

  /**
   * <code>repeated string attributeValues = 3;</code>
   * @return A list containing the attributeValues.
   */
  java.util.List<java.lang.String>
      getAttributeValuesList();
  /**
   * <code>repeated string attributeValues = 3;</code>
   * @return The count of attributeValues.
   */
  int getAttributeValuesCount();
  /**
   * <code>repeated string attributeValues = 3;</code>
   * @param index The index of the element to return.
   * @return The attributeValues at the given index.
   */
  java.lang.String getAttributeValues(int index);
  /**
   * <code>repeated string attributeValues = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the attributeValues at the given index.
   */
  com.google.protobuf.ByteString
      getAttributeValuesBytes(int index);
}
